name: sandeep_jwelery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  animation_wrappers: ^0.0.4
  api_cache_manager: ^1.0.2
  carousel_pro: null
  carousel_slider: ^4.0.0
  chips_choice: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^1.0.1+2
  flutter_keychain: ^2.1.0
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.23.0+1
  fluttertoast: ^8.0.8
  get: ^4.3.8
  getwidget: ^2.0.4
  google_fonts: ^2.1.0
  http: ^0.13.4
  im_stepper: ^0.1.3
  intl: ^0.17.0
  like_button: ^2.0.3
  pin_code_fields: ^7.3.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  shared_value: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logos/
    - assets/icons/
